# -*- coding: utf-8 -*-
"""Uniprot-API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AMkkELEvuawNykHHbw1k3mVh0eu55p-g
"""

#### source: https://www.youtube.com/watch?v=-uoKtReLGVs
import requests, sys, json

WEBSITE_API = "https://rest.uniprot.org/beta"
PROTEINS_API = "https://https://www.ebi.ac.uk/proteins/api"

def get_url(url, **kwargs):
    response = requests.get(url, **kwargs)

    if not response.ok:
        print(response.text)
        response.raise_for_status()
        sys.exit()
    
    return response

"""### Basic search request"""

r = get_url(f'{WEBSITE_API}/uniprotkb/search?query=*')

data = r.json()

n_results = len(data["results"])
print(f"Number of results: {n_results}\n")

#for (key, value) in r.headers.items():
#    print(f'{key}: {value}')

r = get_url(f'{WEBSITE_API}/uniprotkb/search?query=bacterial malate dehydrogenase&fields=length,sequence&format=tsv')

protein_sequence = r.text

protein_list = protein_sequence.split("\n")

with open("bmdh_seq_uniprot.fasta", "w") as f:
    for idx, sq in enumerate(protein_list):
        if idx > 0:
            if len(sq) > 0:
                le = sq.split("\t")[0]
                sq_txt = sq.split("\t")[1]

                if int(le) <= 512:
                    f.write(sq_txt + "\n")
                else:
                    print(le + " excluded.")

# from total of 9853 ref: https://www.uniprot.org/uniprot/?query=bacterial+malate+dehydrogenase&offset=50&sort=score&columns=id%2centry+name%2creviewed%2cprotein+names%2cgenes%2corganism%2clength
r = get_url(f'{WEBSITE_API}/uniprotkb/search?query=bacterial malate dehydrogenase&fields=length,sequence&format=tsv')

i = 1

while r.links.get("next", {}).get("url"):
    
    r = get_url(r.links["next"]["url"])

    #print(r.text)

    protein_sequence = r.text
    protein_list = protein_sequence.split("\n")

    with open("bmdh_seq_uniprot.fasta", "a") as f:
        for idx, sq in enumerate(protein_list):
            if idx > 0:
                print(sq)
                if len(sq) > 0:
                    le = sq.split("\t")[0].split(",")[-1]
                    sq_txt = sq.split("\t")[1]

                    if int(le) <= 512:
                        f.write(sq_txt + "\n")
                    #else:
                    #    print(le + " excluded.")

                    print(i)
                    i = i + 1



